<?php
$root = $container['kernel']['root'];

return array_map('realpath', [
	// $root.'/vendor/asgard/asgard/Container/ContainerAwareTrait.php',
	$root.'/vendor/asgard/asgard/Hook/HookableTrait.php',
	$root.'/vendor/asgard/asgard/Templating/ViewableTrait.php',
	// $root.'/vendor/asgard/behaviors/MetasBehavior.php',
	// $root.'/vendor/asgard/behaviors/PublishBehavior.php',
	// $root.'/vendor/asgard/behaviors/SlugifyBehavior.php',
	// $root.'/vendor/asgard/behaviors/SortableBehavior.php',
	// $root.'/vendor/asgard/behaviors/TimestampsBehavior.php',
	// $root.'/vendor/asgard/asgard/Cache/NullCache.php',
	// $root.'/vendor/asgard/asgard/Common/ArrayUtils.php',
	$root.'/vendor/asgard/asgard/Common/BagInterface.php',
	$root.'/vendor/asgard/asgard/Common/Bag.php',
	// $root.'/vendor/asgard/asgard/Common/DatetimeInterface.php',
	// $root.'/vendor/asgard/asgard/Common/Datetime.php',
	// $root.'/vendor/asgard/asgard/Common/Date.php',
	// $root.'/vendor/asgard/asgard/Common/PaginatorInterface.php',
	// $root.'/vendor/asgard/asgard/Common/Paginator.php',
	// $root.'/vendor/asgard/asgard/Common/PaginatorFactoryInterface.php',
	// $root.'/vendor/asgard/asgard/Common/PaginatorFactory.php',
	// $root.'/vendor/asgard/asgard/Common/Time.php',
	$root.'/vendor/asgard/asgard/Common/Tools.php',
	$root.'/vendor/asgard/asgard/Config/ConfigInterface.php',
	$root.'/vendor/asgard/asgard/Config/Config.php',
	$root.'/vendor/asgard/asgard/Container/ContainerInterface.php',
	$root.'/vendor/asgard/asgard/Container/Container.php',
	$root.'/vendor/asgard/asgard/Container/Facade.php',
	// $root.'/vendor/asgard/asgard/Core/Kernel.php',
	$root.'/vendor/asgard/asgard/Db/DAL.php',
	$root.'/vendor/asgard/asgard/Db/DBInterface.php',
	$root.'/vendor/asgard/asgard/Db/DB.php',
	$root.'/vendor/asgard/asgard/Db/DBException.php',
	$root.'/vendor/asgard/asgard/Db/Query.php',
	$root.'/vendor/asgard/asgard/Db/Raw.php',
	$root.'/vendor/asgard/asgard/Db/SchemaInterface.php',
	$root.'/vendor/asgard/asgard/Db/Schema.php',
	$root.'/vendor/asgard/asgard/Db/SchemaTable.php',
	// $root.'/vendor/asgard/asgard/Debug/Debug.php',
	// $root.'/vendor/asgard/asgard/Debug/ErrorHandler.php',
	// $root.'/vendor/asgard/asgard/Debug/PSRException.php',
	// $root.'/vendor/asgard/asgard/Email/DriverInterface.php',
	// $root.'/vendor/asgard/asgard/Email/FakeEmail.php',
	// $root.'/vendor/asgard/asgard/Email/SwiftMessage.php',
	// $root.'/vendor/asgard/asgard/Entity/Behavior.php',
	// $root.'/vendor/asgard/asgard/Entity/Definition.php',
	// $root.'/vendor/asgard/asgard/Entity/Entity.php',
	// $root.'/vendor/asgard/asgard/Entity/EntityManagerInterface.php',
	// $root.'/vendor/asgard/asgard/Entity/EntityManager.php',
	// $root.'/vendor/asgard/asgard/Entity/File.php',
	// $root.'/vendor/asgard/asgard/Entity/ManyCollection.php',
	// $root.'/vendor/asgard/asgard/Entity/PersistenceBehavior.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/BooleanProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/DateProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/DatetimeProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/EntityProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/FileProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/IntegerProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/StringProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Properties/TextProperty.php',
	// $root.'/vendor/asgard/asgard/Entity/Property.php',
	// $root.'/vendor/asgard/asgard/Entity/RelationsBehavior.php',
	// $root.'/vendor/asgard/asgard/Entity/Serializer.php',
	// $root.'/vendor/asgard/asgard/Form/GroupInterface.php',
	// $root.'/vendor/asgard/asgard/Form/Group.php',
	// $root.'/vendor/asgard/asgard/Form/FormInterface.php',
	// $root.'/vendor/asgard/asgard/Form/Form.php',
	// $root.'/vendor/asgard/asgard/Form/FormException.php',
	// $root.'/vendor/asgard/asgard/Entityform/EntityFieldSolverInterface.php',
	// $root.'/vendor/asgard/asgard/Entityform/EntityFieldSolver.php',
	// $root.'/vendor/asgard/asgard/Entityform/EntityFormInterface.php',
	// $root.'/vendor/asgard/asgard/Entityform/EntityForm.php',
	// $root.'/vendor/asgard/asgard/File/File.php',
	// $root.'/vendor/asgard/asgard/File/FileSystem.php',
	// $root.'/vendor/asgard/asgard/File/Rules/Extension.php',
	// $root.'/vendor/asgard/asgard/Form/DynamicGroup.php',
	// $root.'/vendor/asgard/asgard/Form/Field.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/BooleanField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/CountryField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/CSRFField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/DateField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/DatetimeField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/DayField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/FileField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/HiddenField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/MonthField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/MultipleSelectField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/SelectField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/TextField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/TimeField.php',
	// $root.'/vendor/asgard/asgard/Form/Fields/YearField.php',
	// $root.'/vendor/asgard/asgard/Form/HTMLHelper.php',
	// $root.'/vendor/asgard/asgard/Form/Widget.php',
	// $root.'/vendor/asgard/asgard/Form/WidgetManagerInterface.php',
	// $root.'/vendor/asgard/asgard/Form/WidgetManager.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/CallbackWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/CheckboxesWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/CheckboxWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/DatetimeWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/DateWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/FileWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/HiddenWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/MultipleselectWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/PasswordWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/RadioWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/SelectWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/TextWidget.php',
	// $root.'/vendor/asgard/asgard/Form/Widgets/TimeWidget.php',
	$root.'/vendor/asgard/asgard/Hook/AnnotationReader.php',
	$root.'/vendor/asgard/asgard/Hook/Chain.php',
	$root.'/vendor/asgard/asgard/Hook/HookContainer.php',
	$root.'/vendor/asgard/asgard/Hook/HookManagerInterface.php',
	$root.'/vendor/asgard/asgard/Hook/HookManager.php',
	$root.'/vendor/asgard/asgard/Http/AnnotationReader.php',
	$root.'/vendor/asgard/asgard/Http/Browser/BrowserInterface.php',
	$root.'/vendor/asgard/asgard/Http/Browser/Browser.php',
	$root.'/vendor/asgard/asgard/Http/Controller.php',
	$root.'/vendor/asgard/asgard/Http/Filter.php',
	$root.'/vendor/asgard/asgard/Http/Filters/PageLayout.php',
	$root.'/vendor/asgard/asgard/Http/HttpFile.php',
	$root.'/vendor/asgard/asgard/Http/HttpKernelInterface.php',
	$root.'/vendor/asgard/asgard/Http/HttpKernel.php',
	$root.'/vendor/asgard/asgard/Http/LambdaController.php',
	$root.'/vendor/asgard/asgard/Http/Request.php',
	$root.'/vendor/asgard/asgard/Http/ResolverInterface.php',
	$root.'/vendor/asgard/asgard/Http/Resolver.php',
	$root.'/vendor/asgard/asgard/Http/Response.php',
	$root.'/vendor/asgard/asgard/Http/Route.php',
	$root.'/vendor/asgard/asgard/Http/URLInterface.php',
	$root.'/vendor/asgard/asgard/Http/URL.php',
	$root.'/vendor/asgard/asgard/Http/Utils/HTMLInterface.php',
	$root.'/vendor/asgard/asgard/Http/Utils/HTML.php',
	// $root.'/vendor/asgard/asgard/Migration/Migration.php',
	// $root.'/vendor/asgard/asgard/Migration/MigrationManagerInterface.php',
	// $root.'/vendor/asgard/asgard/Migration/MigrationManager.php',
	// $root.'/vendor/asgard/asgard/Migration/Tracker.php',
	// $root.'/vendor/asgard/asgard/Orm/ORMInterface.php',
	// $root.'/vendor/asgard/asgard/Orm/ORM.php',
	// $root.'/vendor/asgard/asgard/Orm/CollectionORMInterface.php',
	// $root.'/vendor/asgard/asgard/Orm/CollectionORM.php',
	// $root.'/vendor/asgard/asgard/Orm/CollectionORMFactoryInterface.php',
	// $root.'/vendor/asgard/asgard/Orm/CollectionORMFactory.php',
	// $root.'/vendor/asgard/asgard/Orm/DataMapperInterface.php',
	// $root.'/vendor/asgard/asgard/Orm/DataMapper.php',
	// $root.'/vendor/asgard/asgard/Orm/EntityRelation.php',
	// $root.'/vendor/asgard/asgard/Orm/ORMBehavior.php',
	// $root.'/vendor/asgard/asgard/Orm/ORMFactoryInterface.php',
	// $root.'/vendor/asgard/asgard/Orm/ORMFactory.php',
	// $root.'/vendor/asgard/asgard/Orm/ORMMigrations.php',
	// $root.'/vendor/asgard/asgard/Orm/PolymorphicCollectionORM.php',
	// $root.'/vendor/asgard/asgard/Orm/Rules/Ormhasmorethan.php',
	// $root.'/vendor/asgard/asgard/Orm/Rules/Ormrequired.php',
	// $root.'/vendor/asgard/asgard/Orm/Rules/Unique.php',
	$root.'/vendor/asgard/asgard/Templating/TemplateEngineFactoryInterface.php',
	$root.'/vendor/asgard/asgard/Templating/TemplateEngineInterface.php',
	$root.'/vendor/asgard/asgard/Templating/TemplateInterface.php',
	$root.'/vendor/asgard/asgard/Templating/PHPTemplate.php',
	// $root.'/vendor/asgard/asgard/Validation/InputBag.php',
	// $root.'/vendor/asgard/asgard/Validation/Report.php',
	// $root.'/vendor/asgard/asgard/Validation/Rule.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/All.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Any.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Callback.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Contains.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Date.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Each.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Email.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Equal.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Int.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Isinstanceof.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Length.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Lengthbetween.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Max.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Maxlength.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Min.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Minlength.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Regex.php',
	// $root.'/vendor/asgard/asgard/Validation/Rules/Same.php',
	// $root.'/vendor/asgard/asgard/Validation/RulesRegistryInterface.php',
	// $root.'/vendor/asgard/asgard/Validation/RulesRegistry.php',
	// $root.'/vendor/asgard/asgard/Validation/Validator.php',
	// $root.'/vendor/asgard/asgard/Validation/ValidatorException.php',
	// $root.'/vendor/asgard/asgard/Validation/ValidatorFactoryInterface.php',
	// $root.'/vendor/asgard/asgard/Validation/ValidatorInterface.php',
	// $root.'/vendor/asgard/asgard/Validation/ValidatorFactory.php',
	// $root.'/vendor/asgard/vendor/nesbot/carbon/src/Carbon/Carbon.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/Annotation/Target.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocLexer.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/Reader.php',
	$root.'/vendor/asgard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/SimpleAnnotationReader.php',
	// $root.'/vendor/asgard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/Cache.php',
	// $root.'/vendor/asgard/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php',
	// $root.'/vendor/asgard/vendor/doctrine/lexer/lib/Doctrine/Common/Lexer/AbstractLexer.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Connection.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/ExceptionConverterDriver.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Events.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/Keywords/KeywordList.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/Keywords/SQLiteKeywords.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/Expression/ExpressionBuilder.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractAsset.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Column.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/ColumnDiff.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Comparator.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Constraint.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Identifier.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Index.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaConfig.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/TableDiff.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/AbstractVisitor.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/NamespaceVisitor.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/Visitor.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/StringType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BigIntType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BinaryType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BooleanType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeTzType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DecimalType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/FloatType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/GuidType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/IntegerType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/JsonArrayType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ObjectType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/SimpleArrayType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/SmallIntType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/TextType.php',
	// $root.'/vendor/asgard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/TimeType.php',
	// $root.'/vendor/doctrine/instantiator/src/Doctrine/Instantiator/InstantiatorInterface.php',
	// $root.'/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php',
	$root.'/vendor/asgard/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php',
	// $root.'/vendor/asgard/vendor/psr/log/Psr/Log/LoggerInterface.php',
	// $root.'/vendor/asgard/vendor/psr/log/Psr/Log/LogLevel.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/MessageCatalogueInterface.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/MessageCatalogue.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/MetadataAwareInterface.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/MessageSelector.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/TranslatorBagInterface.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/TranslatorInterface.php',
	// $root.'/vendor/asgard/vendor/symfony/translation/Symfony/Component/Translation/Translator.php',
	// $root.'/vendor/asgard/vendor/symfony/yaml/Symfony/Component/Yaml/Inline.php',
	// $root.'/vendor/asgard/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php',
]);